name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**/*.py"
      - "pyproject.toml"
      - "uv.lock"
      - "Makefile"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "src/**/*.py"
      - "pyproject.toml"
      - "uv.lock"
      - "Makefile"
      - ".github/workflows/ci.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv sync
      - run: make check
