name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**/*.py"
  pull_request:
    paths:
      - "src/**/*.py"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv sync
      - run: make check
